Feature dynamic gbt
bitprim/bitprim-node pull request #16
Opened 2018-06-15 13:53 UTC by ramacarlucho

2018-06-15 14:04 UTC, dario-ramos submitted a review, later dismissed

2018-06-18 18:32 UTC, mdallago commented on include/bitcoin/node/full_node.hpp
> +    mutable std::mutex gbt_mutex_;
move to blockchain

2018-06-18 18:32 UTC, mdallago commented on src/protocols/protocol_block_in.cpp
> +    chain_.remove_mined_txs_from_mempool(message);
move to blockchain

2018-06-18 18:32 UTC, mdallago commented on src/protocols/protocol_transaction_in.cpp
> +    chain_.add_to_chosen_list(message);
move to blockchain

2018-07-06 16:07 UTC, dario-ramos submitted a review, later dismissed

2018-07-11 19:38 UTC, hanchon submitted a review, later dismissed

2018-07-11 19:48 UTC, fpelliccioni requested changes

2018-07-11 19:48 UTC, fpelliccioni commented on include/bitcoin/node/full_node.hpp
> +    mutable std::mutex gbt_mutex_;
the mutex is not used here, have to be a member of blockchain

2018-07-12 22:51 UTC, fpelliccioni approved these changes

2018-07-13 13:19 UTC, mdallago commented on src/protocols/protocol_block_in.cpp
> +    chain_.remove_mined_txs_from_mempool(message);
pending

2018-07-13 13:19 UTC, mdallago commented on src/protocols/protocol_transaction_in.cpp
> +    chain_.add_to_chosen_list(message);
pending

2018-07-13 13:20 UTC, mdallago reviewed
pending items

2018-07-13 13:20 UTC, mdallago approved these changes

2018-07-16 15:46 UTC, fpelliccioni approved these changes
Needs a refactoring for the next version

2018-07-16 19:31 UTC, merged